#!/usr/bin/env python
"""Slot-level continuous miner for large-scale BRAIN simulations.

This is the sturdier project-native absorption of worldquant-miner's best idea:
keep a fixed number of simulation slots busy, and refill a slot immediately
after it completes. It deliberately reuses this project's safer assets:
- supply jobs/templates generated by continuous_supply_engine.py
- shared field inventories
- fingerprint de-duplication
- local result storage and platform color sync from brain_client.py
- structured 429 telemetry and adaptive concurrency

It does not final-submit alphas.
"""

from __future__ import annotations

import argparse
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait
from dataclasses import dataclass
from datetime import datetime, timezone
import json
import math
from pathlib import Path
import random
import re
import subprocess
import sys
import threading
import time
from time import sleep

import yaml


ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from brain_client import (  # noqa: E402
    CREDENTIALS_FILE,
    build_alpha_fingerprint,
    load_credentials,
    login,
    submit_alpha_config,
)
from script.batch_runtime import load_tested_fingerprints  # noqa: E402
from script.field_selection_engine import extract_template_context, score_field_record  # noqa: E402
from script.submit_template_loop import extract_field_slots, load_template, replace_field_map, slugify  # noqa: E402
from script.template_validator import validate_template_payload  # noqa: E402


SCRIPT_DIR = ROOT_DIR / "script"
SUPPLY_JOBS_FILE = ROOT_DIR / "result_store" / "supply" / "supply_jobs.json"
INVENTORY_DIR = ROOT_DIR / "result_store" / "inventories"
SUMMARY_DIR = ROOT_DIR / "result_store" / "summaries"
RATE_LIMIT_EVENTS_FILE = ROOT_DIR / "result_store" / "analysis" / "logs" / "rate_limit_events.jsonl"
STATE_DIR = ROOT_DIR / "result_store" / "slot_miner"
RUNTIME_GUARDRAILS_FILE = ROOT_DIR / "result_store" / "analysis" / "runtime_guardrails.json"
RAW_FAMILY_ACTIONS_FILE = ROOT_DIR / "result_store" / "analysis" / "raw_family_actions.json"
RAW_FAMILY_ARCHIVE_FILE = ROOT_DIR / "result_store" / "analysis" / "raw_family_archive.json"
THREAD_LOCAL = threading.local()
SESSION_REFRESH_SECONDS = 3 * 60 * 60
OPERATOR_WRAPPER_MAP = {
    "vector_neut": ["vector_neut_volume", "vector_neut_returns"],
    "regression_neut": ["regression_neut_volatility"],
}


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def load_config(path: Path) -> dict:
    payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Invalid slot miner config: {path}")
    return payload


def run_command(command: list[str], cwd: Path) -> int:
    print("=" * 80)
    print("RUN:", " ".join(command))
    print("=" * 80)
    completed = subprocess.run(command, cwd=str(cwd), check=False)
    print(f"EXIT CODE: {completed.returncode}")
    return completed.returncode


def build_supply(config_path: Path) -> int:
    return run_command(
        [sys.executable, str(SCRIPT_DIR / "continuous_supply_engine.py"), str(config_path)],
        ROOT_DIR,
    )


def load_supply_jobs() -> list[dict]:
    if not SUPPLY_JOBS_FILE.exists():
        return []
    try:
        payload = json.loads(SUPPLY_JOBS_FILE.read_text(encoding="utf-8"))
    except Exception:
        return []
    jobs = payload.get("jobs")
    return jobs if isinstance(jobs, list) else []


def load_supply_summary() -> dict:
    if not SUPPLY_JOBS_FILE.exists():
        return {}
    try:
        payload = json.loads(SUPPLY_JOBS_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def state_path_for(name: str) -> Path:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    return STATE_DIR / f"{name}.json"


def load_state(path: Path) -> dict:
    if not path.exists():
        return {
            "started_at": utc_now(),
            "completed": 0,
            "errors": 0,
            "attempted_fingerprints": [],
            "attempted_keys": [],
            "known_bad_fingerprints": [],
            "known_bad_keys": [],
            "attempt_generation_id": 0,
            "template_error_counts": {},
            "error_kind_counts": {},
            "candidate_scan_stats": {},
            "last_submit_at": None,
            "last_submit_alpha_id": None,
            "history": [],
            "mechanism_cursor": 0,
            "mechanism_attempt_counts": {},
        }
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        payload = {}
    if not isinstance(payload, dict):
        payload = {}
    payload.setdefault("started_at", utc_now())
    payload.setdefault("completed", 0)
    payload.setdefault("errors", 0)
    payload.setdefault("attempted_fingerprints", [])
    payload.setdefault("attempted_keys", [])
    payload.setdefault("known_bad_fingerprints", [])
    payload.setdefault("known_bad_keys", [])
    payload.setdefault("attempt_generation_id", 0)
    payload.setdefault("template_error_counts", {})
    payload.setdefault("error_kind_counts", {})
    payload.setdefault("candidate_scan_stats", {})
    payload.setdefault("last_submit_at", None)
    payload.setdefault("last_submit_alpha_id", None)
    payload.setdefault("history", [])
    payload.setdefault("job_bandit", {})
    payload.setdefault("optimizer", {})
    payload.setdefault("mechanism_cursor", 0)
    payload.setdefault("mechanism_attempt_counts", {})
    return payload


def save_state(path: Path, state: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state, ensure_ascii=False, indent=2), encoding="utf-8")


def load_runtime_guardrails() -> dict:
    if not RUNTIME_GUARDRAILS_FILE.exists():
        return {}
    try:
        payload = json.loads(RUNTIME_GUARDRAILS_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def save_runtime_guardrails(payload: dict) -> None:
    RUNTIME_GUARDRAILS_FILE.parent.mkdir(parents=True, exist_ok=True)
    payload["updated_at"] = utc_now()
    RUNTIME_GUARDRAILS_FILE.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def load_raw_family_actions_payload() -> dict:
    if not RAW_FAMILY_ACTIONS_FILE.exists():
        return {"schema_version": 1, "family_count": 0, "actions": []}
    try:
        payload = json.loads(RAW_FAMILY_ACTIONS_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {"schema_version": 1, "family_count": 0, "actions": []}
    if not isinstance(payload, dict):
        return {"schema_version": 1, "family_count": 0, "actions": []}
    payload.setdefault("schema_version", 1)
    payload.setdefault("actions", [])
    return payload


def save_raw_family_actions_payload(payload: dict) -> None:
    actions = payload.get("actions")
    if not isinstance(actions, list):
        payload["actions"] = []
    payload["family_count"] = len(payload["actions"])
    payload["updated_at"] = utc_now()
    RAW_FAMILY_ACTIONS_FILE.parent.mkdir(parents=True, exist_ok=True)
    RAW_FAMILY_ACTIONS_FILE.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def load_raw_family_archive_payload() -> dict:
    if not RAW_FAMILY_ARCHIVE_FILE.exists():
        return {"schema_version": 1, "used_families": []}
    try:
        payload = json.loads(RAW_FAMILY_ARCHIVE_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {"schema_version": 1, "used_families": []}
    if not isinstance(payload, dict):
        return {"schema_version": 1, "used_families": []}
    payload.setdefault("schema_version", 1)
    payload.setdefault("used_families", [])
    return payload


def save_raw_family_archive_payload(payload: dict) -> None:
    used = payload.get("used_families")
    if not isinstance(used, list):
        payload["used_families"] = []
    payload["updated_at"] = utc_now()
    RAW_FAMILY_ARCHIVE_FILE.parent.mkdir(parents=True, exist_ok=True)
    RAW_FAMILY_ARCHIVE_FILE.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def archive_raw_family_from_runtime(family: str, reason: str) -> None:
    family = str(family or "").strip()
    if not family:
        return
    payload = load_raw_family_archive_payload()
    used = [str(item) for item in (payload.get("used_families") or []) if str(item)]
    if family not in set(used):
        used.append(family)
        payload["used_families"] = used
        payload["runtime_archive_reason"] = reason
        save_raw_family_archive_payload(payload)


def pause_raw_family_by_name(family: str, reason: str, evidence: dict | None = None) -> None:
    family = str(family or "").strip()
    if not family:
        return
    payload = load_raw_family_actions_payload()
    actions = payload.get("actions") or []
    existing = None
    for row in actions:
        if isinstance(row, dict) and str(row.get("family") or "") == family:
            existing = row
            break
    if existing is None:
        existing = {"family": family}
        actions.append(existing)
    existing_evidence = existing.get("evidence")
    if not isinstance(existing_evidence, dict):
        existing_evidence = {}
    existing_evidence.update(evidence or {})
    existing_evidence["runtime_pause_reason"] = reason
    existing_evidence["runtime_pause_triggered_at"] = utc_now()
    existing.update(
        {
            "decision": "retire",
            "resource_action": "pause_rotation_due_to_no_candidate",
            "priority_delta": -3.5,
            "dataset_lanes_target": 0,
            "max_jobs_multiplier": 0.0,
            "rotation_paused": True,
            "refine_focus": ["fresh_family_required", "rebuild_supply"],
            "evidence": existing_evidence,
        }
    )
    payload["actions"] = actions
    save_raw_family_actions_payload(payload)
    archive_raw_family_from_runtime(family, reason)
    print(f"[RAW FAMILY PAUSE] {family} | reason={reason}")


def pause_raw_family_rotation(family: str, reason: str, error_kind: str, candidate: "Candidate") -> None:
    family = str(family or "").strip()
    if not family:
        return
    payload = load_raw_family_actions_payload()
    actions = payload.get("actions") or []
    existing = None
    for row in actions:
        if isinstance(row, dict) and str(row.get("family") or "") == family:
            existing = row
            break
    if existing is None:
        existing = {"family": family}
        actions.append(existing)
    evidence = existing.get("evidence")
    if not isinstance(evidence, dict):
        evidence = {}
    evidence["retire_reason"] = reason
    evidence["top_error_kind"] = error_kind
    evidence["structural_pause_triggered_at"] = utc_now()
    evidence["trigger_job"] = candidate.job_name
    evidence["trigger_template"] = str(candidate.template_path.relative_to(ROOT_DIR))
    existing.update(
        {
            "decision": "retire",
            "resource_action": "pause_rotation_due_to_structural_template_field_incompatibility",
            "priority_delta": -3.5,
            "dataset_lanes_target": 0,
            "max_jobs_multiplier": 0.0,
            "rotation_paused": True,
            "refine_focus": ["fix_template_field_compatibility", "rebuild_inventories"],
            "evidence": evidence,
        }
    )
    payload["actions"] = actions
    save_raw_family_actions_payload(payload)
    print(f"[RAW FAMILY PAUSE] {family} | reason={reason} | error_kind={error_kind}")


def disable_operator_from_error(message: str, source: str = "") -> bool:
    match = re.search(r'unknown operator "([^"]+)"', str(message or ""), flags=re.IGNORECASE)
    if not match:
        match = re.search(r'inaccessible or unknown operator "([^"]+)"', str(message or ""), flags=re.IGNORECASE)
    if not match:
        return False
    operator = match.group(1).strip()
    wrappers = OPERATOR_WRAPPER_MAP.get(operator, [])
    if not wrappers:
        return False
    payload = load_runtime_guardrails()
    disabled_wrappers = list(payload.get("disabled_wrappers") or [])
    disabled_operators = list(payload.get("disabled_operators") or [])
    changed = False
    for wrapper in wrappers:
        if wrapper not in disabled_wrappers:
            disabled_wrappers.append(wrapper)
            changed = True
    if operator not in disabled_operators:
        disabled_operators.append(operator)
        changed = True
    if not changed:
        return False
    events = list(payload.get("events") or [])
    events.append(
        {
            "ts": utc_now(),
            "event": "operator_disabled",
            "operator": operator,
            "wrappers": wrappers,
            "source": source,
        }
    )
    payload["disabled_wrappers"] = disabled_wrappers[-100:]
    payload["disabled_operators"] = disabled_operators[-100:]
    payload["events"] = events[-300:]
    save_runtime_guardrails(payload)
    print(f"[RUNTIME GUARDRAIL] disabled operator={operator} wrappers={wrappers} source={source}")
    return True


def inventory_guardrail_key(job: dict) -> str:
    return str(job.get("inventory_name") or job.get("name") or Path(str(job.get("template"))).stem)


def inventory_is_paused(job: dict) -> tuple[bool, dict]:
    key = inventory_guardrail_key(job)
    payload = load_runtime_guardrails()
    inventories = payload.get("paused_inventories") or {}
    row = inventories.get(key) if isinstance(inventories, dict) else None
    if not isinstance(row, dict):
        return False, {}
    until_raw = row.get("paused_until")
    try:
        until_ts = datetime.fromisoformat(str(until_raw).replace("Z", "+00:00")).timestamp()
    except Exception:
        return False, row
    return datetime.now(timezone.utc).timestamp() < until_ts, row


def pause_inventory(job: dict, reason: str, minutes: int = 240) -> None:
    key = inventory_guardrail_key(job)
    payload = load_runtime_guardrails()
    inventories = payload.get("paused_inventories") or {}
    if not isinstance(inventories, dict):
        inventories = {}
    until_ts = datetime.now(timezone.utc).timestamp() + max(5, minutes) * 60
    paused_until = datetime.fromtimestamp(until_ts, timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    row = dict(inventories.get(key) or {})
    row["reason"] = reason
    row["paused_until"] = paused_until
    row["count"] = int(row.get("count") or 0) + 1
    row["last_seen_at"] = utc_now()
    inventories[key] = row
    events = list(payload.get("events") or [])
    events.append({"ts": utc_now(), "event": "inventory_paused", "inventory": key, "reason": reason, "paused_until": paused_until})
    payload["paused_inventories"] = inventories
    payload["events"] = events[-300:]
    save_runtime_guardrails(payload)
    print(f"[INVENTORY PAUSE] {key} | reason={reason} | until={paused_until}")


def append_history(state: dict, event: dict, limit: int = 300) -> None:
    history = state.setdefault("history", [])
    history.append(event)
    if len(history) > limit:
        del history[:-limit]


def append_recent_unique(values: list[str], value: str, limit: int) -> list[str]:
    if not value:
        return values
    updated = [item for item in values if item != value]
    updated.append(value)
    if len(updated) > limit:
        del updated[:-limit]
    return updated


def read_recent_rate_limit_events(window_minutes: int) -> list[dict]:
    if not RATE_LIMIT_EVENTS_FILE.exists():
        return []
    try:
        lines = RATE_LIMIT_EVENTS_FILE.read_text(encoding="utf-8").splitlines()
    except Exception:
        return []

    now = datetime.now(timezone.utc)
    events: list[dict] = []
    for line in reversed(lines):
        line = line.strip()
        if not line:
            continue
        try:
            payload = json.loads(line)
        except Exception:
            continue
        raw_ts = payload.get("ts")
        if not raw_ts:
            continue
        try:
            event_ts = datetime.fromisoformat(str(raw_ts).replace("Z", "+00:00"))
        except Exception:
            continue
        age_minutes = (now - event_ts).total_seconds() / 60
        if age_minutes > window_minutes:
            break
        events.append(payload)
    return events


def choose_adaptive_limits(config: dict, default_active_job_slots: int) -> dict:
    adaptive_cfg = config.get("adaptive_rate_limit") or {}
    if not adaptive_cfg.get("enabled", True):
        return {
            "mode": "disabled",
            "event_count": 0,
            "active_job_slots": max(1, default_active_job_slots),
            "worker_cap": None,
            "cycle_sleep_seconds": None,
        }

    window_minutes = int(adaptive_cfg.get("window_minutes", 15))
    medium_count = int(adaptive_cfg.get("medium_429_count", 8))
    high_count = int(adaptive_cfg.get("high_429_count", 20))
    events = read_recent_rate_limit_events(window_minutes)
    event_count = len(events)

    medium_slots = int(adaptive_cfg.get("medium_active_job_slots", min(default_active_job_slots, 2)))
    high_slots = int(adaptive_cfg.get("high_active_job_slots", 1))
    low_worker_cap = adaptive_cfg.get("low_worker_cap")
    medium_worker_cap = adaptive_cfg.get("medium_worker_cap", 1)
    high_worker_cap = adaptive_cfg.get("high_worker_cap", 1)
    medium_cycle_sleep = adaptive_cfg.get("medium_cycle_sleep_seconds")
    high_cycle_sleep = adaptive_cfg.get("high_cycle_sleep_seconds")

    if event_count >= high_count:
        return {
            "mode": "high",
            "event_count": event_count,
            "active_job_slots": max(1, high_slots),
            "worker_cap": int(high_worker_cap) if high_worker_cap is not None else 1,
            "cycle_sleep_seconds": int(high_cycle_sleep) if high_cycle_sleep is not None else None,
        }
    if event_count >= medium_count:
        return {
            "mode": "medium",
            "event_count": event_count,
            "active_job_slots": max(1, medium_slots),
            "worker_cap": int(medium_worker_cap) if medium_worker_cap is not None else 1,
            "cycle_sleep_seconds": int(medium_cycle_sleep) if medium_cycle_sleep is not None else None,
        }
    return {
        "mode": "low",
        "event_count": event_count,
        "active_job_slots": max(1, default_active_job_slots),
        "worker_cap": int(low_worker_cap) if low_worker_cap is not None else None,
        "cycle_sleep_seconds": None,
    }


def classify_error_kind(message: str | None) -> str:
    text = str(message or "").lower()
    if not text:
        return "unknown"
    if "incorrect authentication credentials" in text or "submit status: 401" in text or "login failed" in text:
        return "auth_expired"
    if "does not support event inputs" in text:
        return "event_input_incompatible"
    if "incompatible unit" in text:
        return "unit_incompatible"
    if "invalid number of inputs" in text:
        return "invalid_input_arity"
    if "does not support group inputs" in text:
        return "group_input_incompatible"
    if "does not support vector inputs" in text:
        return "vector_input_incompatible"
    if "429" in text or "rate-limited" in text or "concurrent limit reached" in text:
        return "rate_limited"
    if "simulation polling timed out" in text or "simulation polling stalled" in text:
        return "simulation_poll_timeout"
    if "unknown variable" in text:
        return "unknown_variable"
    if "simulation finished without alpha id" in text:
        return "simulation_error_without_alpha_id"
    return "unknown"


def error_kind_is_structural(kind: str) -> bool:
    return kind in {
        "event_input_incompatible",
        "unit_incompatible",
        "invalid_input_arity",
        "group_input_incompatible",
        "vector_input_incompatible",
        "unknown_variable",
        "simulation_error_without_alpha_id",
    }


def extract_unknown_variable(message: str | None) -> str:
    match = re.search(r'unknown variable "([^"]+)"', str(message or ""), flags=re.IGNORECASE)
    if not match:
        return ""
    return match.group(1).strip()


def invalidate_session() -> None:
    if hasattr(THREAD_LOCAL, "session"):
        try:
            THREAD_LOCAL.session.close()
        except Exception:
            pass
        delattr(THREAD_LOCAL, "session")
    if hasattr(THREAD_LOCAL, "session_created_at"):
        delattr(THREAD_LOCAL, "session_created_at")


def is_auth_error(exc: Exception) -> bool:
    text = str(exc or "").lower()
    return (
        "incorrect authentication credentials" in text
        or "submit status: 401" in text
        or "401 client error" in text
        or "login failed" in text
    )


def reset_attempt_tracking_for_generation(
    state: dict,
    generation_id: int,
    fingerprint_limit: int = 1200,
    key_limit: int = 2400,
) -> bool:
    current_generation = int(state.get("attempt_generation_id") or 0)
    if current_generation != generation_id:
        state["attempt_generation_id"] = generation_id
        state["attempted_fingerprints"] = []
        state["attempted_keys"] = []
        state["template_error_counts"] = {}
        append_history(
            state,
            {
                "ts": utc_now(),
                "event": "attempt_tracking_reset",
                "generation_id": generation_id,
                "previous_generation_id": current_generation,
            },
        )
        return True

    state["attempted_fingerprints"] = list(state.get("attempted_fingerprints") or [])[-fingerprint_limit:]
    state["attempted_keys"] = list(state.get("attempted_keys") or [])[-key_limit:]
    return False


def recover_stale_submission_flow(
    state: dict,
    supply_summary: dict,
    stale_minutes: int,
    active_running: int,
) -> bool:
    if stale_minutes <= 0 or active_running > 0:
        return False
    last_submit_at = iso_to_timestamp(state.get("last_submit_at"))
    if last_submit_at is None:
        return False
    stale_seconds = max(60, stale_minutes * 60)
    if datetime.now(timezone.utc).timestamp() - last_submit_at < stale_seconds:
        return False
    generation_id = int(supply_summary.get("generation_id") or 0)
    state["attempted_fingerprints"] = []
    state["attempted_keys"] = []
    state["template_error_counts"] = {}
    state["attempt_generation_id"] = generation_id
    append_history(
        state,
        {
            "ts": utc_now(),
            "event": "stale_submit_recovery",
            "generation_id": generation_id,
            "last_submit_at": state.get("last_submit_at"),
            "stale_minutes": stale_minutes,
        },
    )
    return True


def _safe_float(value, default: float = 0.0) -> float:
    try:
        if value is None:
            return default
        return float(value)
    except Exception:
        return default


def iso_to_timestamp(value: str | None) -> float | None:
    if not value:
        return None
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00")).timestamp()
    except Exception:
        return None


def reward_from_result(result: dict) -> float:
    details = result.get("alpha_details") or {}
    is_block = details.get("is") or {}
    sharpe = _safe_float(is_block.get("sharpe"))
    fitness = _safe_float(is_block.get("fitness"))
    returns = _safe_float(is_block.get("returns"))
    margin = _safe_float(is_block.get("margin"))
    turnover = abs(_safe_float(is_block.get("turnover")))
    reward = sharpe * 0.45 + fitness * 0.35 + returns * 3.0 + margin * 150.0
    if sharpe > 2.0 and fitness > 2.0:
        reward += 0.4
    if turnover > 0.7:
        reward -= 0.3
    return reward


def ensure_optimizer_state(state: dict, miner_cfg: dict) -> dict:
    optimizer = state.setdefault("optimizer", {})
    optimizer.setdefault("exploration_rate", float(miner_cfg.get("initial_exploration_rate", 0.28)))
    optimizer.setdefault("min_exploration_rate", float(miner_cfg.get("min_exploration_rate", 0.08)))
    optimizer.setdefault("max_exploration_rate", float(miner_cfg.get("max_exploration_rate", 0.55)))
    optimizer.setdefault("optimization_interval", int(miner_cfg.get("optimization_interval", 18)))
    optimizer.setdefault("last_optimized_completed", 0)
    optimizer.setdefault("recent_rewards", [])
    optimizer.setdefault("recent_status", [])
    return optimizer


def update_optimizer_from_reward(state: dict, reward: float, success: bool, miner_cfg: dict) -> None:
    optimizer = ensure_optimizer_state(state, miner_cfg)
    rewards = optimizer.setdefault("recent_rewards", [])
    statuses = optimizer.setdefault("recent_status", [])
    rewards.append(reward)
    statuses.append(1 if success else 0)
    if len(rewards) > 120:
        del rewards[:-120]
    if len(statuses) > 120:
        del statuses[:-120]

    completed = int(state.get("completed") or 0) + int(state.get("errors") or 0)
    interval = int(optimizer.get("optimization_interval") or 18)
    last_optimized = int(optimizer.get("last_optimized_completed") or 0)
    if completed - last_optimized < interval:
        return

    recent_rewards = rewards[-interval:]
    recent_statuses = statuses[-interval:]
    avg_reward = sum(recent_rewards) / max(len(recent_rewards), 1)
    success_rate = sum(recent_statuses) / max(len(recent_statuses), 1)
    exploration_rate = float(optimizer.get("exploration_rate") or 0.28)
    min_rate = float(optimizer.get("min_exploration_rate") or 0.08)
    max_rate = float(optimizer.get("max_exploration_rate") or 0.55)

    if success_rate < 0.22 or avg_reward < 0.8:
        exploration_rate = min(max_rate, exploration_rate * 1.12)
    elif success_rate > 0.4 and avg_reward > 1.4:
        exploration_rate = max(min_rate, exploration_rate * 0.92)
    elif avg_reward > 1.0:
        exploration_rate = max(min_rate, exploration_rate * 0.97)

    optimizer["exploration_rate"] = round(exploration_rate, 4)
    optimizer["last_optimized_completed"] = completed
    optimizer["last_avg_reward"] = round(avg_reward, 6)
    optimizer["last_success_rate"] = round(success_rate, 6)


def update_job_bandit(state: dict, job_name: str, reward: float, success: bool) -> None:
    bandit = state.setdefault("job_bandit", {})
    arm = bandit.setdefault(
        job_name,
        {
            "alpha": 1.0,
            "beta": 1.0,
            "pulls": 0,
            "reward_sum": 0.0,
            "avg_reward": 0.0,
            "successes": 0,
        },
    )
    arm["pulls"] = int(arm.get("pulls") or 0) + 1
    arm["reward_sum"] = _safe_float(arm.get("reward_sum")) + reward
    arm["avg_reward"] = arm["reward_sum"] / max(arm["pulls"], 1)
    if success:
        arm["successes"] = int(arm.get("successes") or 0) + 1
    normalized_reward = max(0.0, min(1.0, (reward + 1.0) / 2.0))
    arm["alpha"] = _safe_float(arm.get("alpha"), 1.0) + normalized_reward
    arm["beta"] = _safe_float(arm.get("beta"), 1.0) + (1.0 - normalized_reward)


def job_sampling_score(job: dict, state: dict, exploration_rate: float) -> float:
    base_priority = _safe_float(job.get("supply_priority"))
    job_name = str(job.get("name") or "")
    bandit = state.get("job_bandit") or {}
    arm = bandit.get(job_name) or {}
    alpha = max(_safe_float(arm.get("alpha"), 1.0), 0.01)
    beta = max(_safe_float(arm.get("beta"), 1.0), 0.01)
    sampled = random.betavariate(alpha, beta)
    avg_reward = _safe_float(arm.get("avg_reward"))
    pulls = int(arm.get("pulls") or 0)
    confidence_bonus = min(0.35, math.log1p(max(pulls, 0)) / 15.0)
    random_jitter = random.random() * max(0.05, exploration_rate * 0.6)
    raw_alpha_bonus = 0.0
    if job.get("raw_alpha_family"):
        raw_alpha_bonus = 0.75
        if pulls == 0:
            raw_alpha_bonus += 0.35
    return base_priority + raw_alpha_bonus + sampled * 0.9 + avg_reward * 0.08 + confidence_bonus + random_jitter


def choose_desired_mode(base_mode: str, supply_summary: dict, state: dict, miner_cfg: dict) -> str:
    optimizer = ensure_optimizer_state(state, miner_cfg)
    exploration_rate = float(optimizer.get("exploration_rate") or 0.28)
    search_strategy = supply_summary.get("search_strategy") or {}
    exploit_share = _safe_float(search_strategy.get("exploit_share"), 0.5)
    if random.random() < exploration_rate:
        return "explore"
    if base_mode == "exploit" and random.random() < max(0.35, exploit_share):
        return "exploit"
    if base_mode == "explore" and random.random() < max(0.35, 1.0 - exploit_share):
        return "explore"
    return base_mode


def inventory_file_for(job: dict) -> Path:
    inventory_name = str(job.get("inventory_name") or job.get("name") or Path(str(job.get("template"))).stem)
    return INVENTORY_DIR / f"{inventory_name}.txt"


def inventory_json_for(job: dict) -> Path:
    inventory_name = str(job.get("inventory_name") or job.get("name") or Path(str(job.get("template"))).stem)
    return INVENTORY_DIR / f"{inventory_name}.json"


def load_job_template_context(job: dict) -> dict | None:
    template_ref = str(job.get("template") or "").strip()
    if not template_ref:
        return None
    try:
        template = load_template(resolve_template(template_ref))
    except Exception:
        return None
    return extract_template_context(template, selection_query=job.get("selection_query"))


def field_is_compatible_with_job(field: dict, job: dict) -> tuple[bool, list[str]]:
    context = load_job_template_context(job)
    if context is None:
        return True, []
    decision = score_field_record(field, context)
    return decision.score >= 0, list(decision.reasons)


def inventory_compatibility_report(job: dict) -> dict:
    path = inventory_json_for(job)
    report = {
        "checked": False,
        "incompatible_count": 0,
        "field_type_counts": {},
        "sample_incompatible": [],
        "missing_compatibility_metadata": False,
    }
    if not path.exists():
        return report
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return report
    fields = payload.get("fields") if isinstance(payload, dict) else []
    if not isinstance(fields, list):
        return report
    context = load_job_template_context(job)
    if context is None:
        return report
    report["checked"] = True
    if "compatible_record_count" not in payload and not payload.get("compatibility_checked_at"):
        report["missing_compatibility_metadata"] = True
    type_counts: dict[str, int] = {}
    sample: list[dict] = []
    incompatible_count = 0
    for field in fields:
        if not isinstance(field, dict):
            continue
        field_type = str(field.get("type") or "UNKNOWN").upper()
        type_counts[field_type] = type_counts.get(field_type, 0) + 1
        decision = score_field_record(field, context)
        if decision.score >= 0:
            continue
        incompatible_count += 1
        if len(sample) < 8:
            sample.append(
                {
                    "id": field.get("id"),
                    "type": field_type,
                    "reasons": decision.reasons,
                }
            )
    report["field_type_counts"] = type_counts
    report["incompatible_count"] = incompatible_count
    report["sample_incompatible"] = sample
    return report


def stamp_inventory_compatibility(job: dict) -> None:
    path = inventory_json_for(job)
    if not path.exists():
        return
    report = inventory_compatibility_report(job)
    if not report.get("checked") or int(report.get("incompatible_count") or 0) > 0:
        return
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return
    payload["compatibility_checked_at"] = utc_now()
    payload["compatibility_field_type_counts"] = report.get("field_type_counts") or {}
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def sanitize_inventory_to_compatible_fields(job: dict) -> int:
    path = inventory_json_for(job)
    if not path.exists():
        return len(load_inventory_fields(job))
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return len(load_inventory_fields(job))
    fields = payload.get("fields") if isinstance(payload, dict) else []
    if not isinstance(fields, list):
        return len(load_inventory_fields(job))
    compatible_fields: list[dict] = []
    removed_fields: list[dict] = []
    for field in fields:
        if not isinstance(field, dict):
            continue
        compatible, reasons = field_is_compatible_with_job(field, job)
        if compatible:
            compatible_fields.append(field)
        elif len(removed_fields) < 20:
            removed_fields.append(
                {
                    "id": field.get("id"),
                    "type": field.get("type"),
                    "reasons": reasons,
                }
            )
    payload["fields"] = compatible_fields
    payload["selected_record_count"] = len(compatible_fields)
    payload["compatible_record_count"] = len(compatible_fields)
    payload["compatibility_checked_at"] = utc_now()
    payload["compatibility_sanitized_at"] = utc_now()
    payload["compatibility_removed_count"] = max(0, len(fields) - len(compatible_fields))
    payload["compatibility_removed_sample"] = removed_fields
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    txt_path = inventory_file_for(job)
    txt_path.write_text(
        "\n".join(str(field.get("id") or "") for field in compatible_fields if field.get("id")) + "\n",
        encoding="utf-8",
    )
    if removed_fields:
        print(
            f"[INVENTORY SANITIZE] {path.stem} | kept={len(compatible_fields)} | "
            f"removed={len(fields) - len(compatible_fields)} | sample={removed_fields[:5]}"
        )
    return len(compatible_fields)


def slot_inventory_specs(job: dict) -> dict[str, dict]:
    payload = job.get("slot_inventories") or {}
    return payload if isinstance(payload, dict) else {}


def load_inventory_fields(job: dict) -> list[str]:
    path = inventory_file_for(job)
    if not path.exists():
        return []
    field_ids = [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    json_path = inventory_json_for(job)
    if not json_path.exists():
        return field_ids
    try:
        payload = json.loads(json_path.read_text(encoding="utf-8"))
    except Exception:
        return field_ids
    fields = payload.get("fields") if isinstance(payload, dict) else []
    if not isinstance(fields, list):
        return field_ids
    compatible_ids: set[str] = set()
    for field in fields:
        if not isinstance(field, dict):
            continue
        field_id = str(field.get("id") or "").strip()
        if not field_id:
            continue
        compatible, _ = field_is_compatible_with_job(field, job)
        if compatible:
            compatible_ids.add(field_id)
    if not compatible_ids:
        return []
    return [field_id for field_id in field_ids if field_id in compatible_ids]


def bad_field_set(state: dict) -> set[str]:
    return {
        str(item).strip()
        for item in (state.get("known_bad_fields") or [])
        if str(item).strip()
    }


def remember_bad_field(state: dict, field: str, limit: int = 500) -> None:
    field = str(field or "").strip()
    if not field:
        return
    values = append_recent_unique(list(state.get("known_bad_fields") or []), field, limit)
    state["known_bad_fields"] = values


def load_slot_inventory_fields(job: dict, slot: str) -> list[str]:
    specs = slot_inventory_specs(job)
    spec = specs.get(slot)
    if not isinstance(spec, dict):
        return load_inventory_fields(job)
    return load_inventory_fields(spec)


def load_inventory_state(job: dict) -> dict:
    inventory_name = str(job.get("inventory_name") or job.get("name") or Path(str(job.get("template"))).stem)
    inventory_path = inventory_json_for(job)
    summary_path = SUMMARY_DIR / f"{inventory_name}.json"
    payload = {
        "inventory_name": inventory_name,
        "inventory_exists": inventory_path.exists(),
        "selected_count": 0,
        "completed_count": 0,
        "pool_size": 0,
        "age_minutes": None,
        "hydrated_from_related": False,
        "min_coverage": None,
        "compatibility_checked": False,
        "incompatible_count": 0,
        "field_type_counts": {},
        "missing_compatibility_metadata": False,
    }
    if inventory_path.exists():
        try:
            inventory_payload = json.loads(inventory_path.read_text(encoding="utf-8"))
        except Exception:
            inventory_payload = {}
        payload["selected_count"] = int(inventory_payload.get("selected_record_count") or 0)
        payload["hydrated_from_related"] = bool(inventory_payload.get("hydrated_from_related_inventories"))
        payload["min_coverage"] = inventory_payload.get("min_coverage")
        age_seconds = max(0.0, datetime.now(timezone.utc).timestamp() - inventory_path.stat().st_mtime)
        payload["age_minutes"] = age_seconds / 60
        compatibility = inventory_compatibility_report(job)
        payload["compatibility_checked"] = bool(compatibility.get("checked"))
        payload["incompatible_count"] = int(compatibility.get("incompatible_count") or 0)
        payload["field_type_counts"] = compatibility.get("field_type_counts") or {}
        payload["missing_compatibility_metadata"] = bool(compatibility.get("missing_compatibility_metadata"))
        payload["sample_incompatible"] = compatibility.get("sample_incompatible") or []
    if summary_path.exists():
        try:
            summary_payload = json.loads(summary_path.read_text(encoding="utf-8"))
        except Exception:
            summary_payload = []
        if isinstance(summary_payload, list):
            payload["completed_count"] = len(summary_payload)
    payload["pool_size"] = max(payload["selected_count"] - payload["completed_count"], 0)
    return payload


def relax_inventory_spec(job: dict, inventory_state: dict, reason: str) -> dict:
    relaxed = dict(job)
    original_score = relaxed.get("min_selection_score")
    if original_score is not None:
        try:
            relaxed["min_selection_score"] = max(0.0, float(original_score) - 0.75)
        except Exception:
            relaxed.pop("min_selection_score", None)
    original_limit = int(relaxed.get("selection_limit") or 0)
    if original_limit > 0:
        relaxed["selection_limit"] = max(original_limit, int(original_limit * 2))
    if reason == "empty_selected" and relaxed.get("dataset_id"):
        relaxed.pop("category", None)
    relaxed["inventory_name"] = f"{inventory_state['inventory_name']}_relaxed"
    relaxed["inventory_reuse_min_remaining"] = 1
    relaxed["inventory_stale_after_minutes"] = max(int(relaxed.get("inventory_stale_after_minutes") or 240), 720)
    relaxed["disable_related_hydration"] = True
    print(
        f"[INVENTORY RELAX] {inventory_state['inventory_name']} -> {relaxed['inventory_name']} | "
        f"reason={reason} | min_score={original_score}->{relaxed.get('min_selection_score')} | "
        f"selection_limit={original_limit}->{relaxed.get('selection_limit')}"
    )
    return relaxed


def build_inventory_with_fallback(job: dict, inventory_state: dict, min_pool_size: int) -> bool:
    exit_code = run_command(build_inventory_command(job), ROOT_DIR)
    if exit_code == 0 and len(load_inventory_fields(job)) > 0:
        after_report = inventory_compatibility_report(job)
        if int(after_report.get("incompatible_count") or 0) > 0:
            kept_count = sanitize_inventory_to_compatible_fields(job)
            if kept_count <= 0:
                pause_inventory(job, reason="incompatible_fields_after_inventory_build")
                return False
        stamp_inventory_compatibility(job)
        return True

    after_state = load_inventory_state(job)
    if exit_code != 0:
        return False
    if after_state["selected_count"] > 0:
        after_report = inventory_compatibility_report(job)
        if int(after_report.get("incompatible_count") or 0) > 0:
            kept_count = sanitize_inventory_to_compatible_fields(job)
            if kept_count <= 0:
                pause_inventory(job, reason="incompatible_fields_after_inventory_build")
                return False
        stamp_inventory_compatibility(job)
        return len(load_inventory_fields(job)) > 0

    relaxed = relax_inventory_spec(job, after_state, reason="empty_selected")
    relaxed_state = load_inventory_state(relaxed)
    refresh_relaxed, _ = should_refresh_inventory(relaxed, min_pool_size=max(1, min_pool_size))
    if refresh_relaxed:
        relaxed_exit = run_command(build_inventory_command(relaxed), ROOT_DIR)
        if relaxed_exit != 0:
            pause_inventory(job, reason="relaxed_inventory_build_failed")
            return False
    if len(load_inventory_fields(relaxed)) <= 0:
        pause_inventory(job, reason="empty_after_relaxed_inventory_build")
        return False
    relaxed_report = inventory_compatibility_report(relaxed)
    if int(relaxed_report.get("incompatible_count") or 0) > 0:
        kept_count = sanitize_inventory_to_compatible_fields(relaxed)
        if kept_count <= 0:
            pause_inventory(job, reason="incompatible_fields_after_relaxed_inventory_build")
            return False

    source_txt = inventory_file_for(relaxed)
    source_json = inventory_json_for(relaxed)
    target_txt = inventory_file_for(job)
    target_json = inventory_json_for(job)
    try:
        if source_txt.exists():
            target_txt.write_text(source_txt.read_text(encoding="utf-8"), encoding="utf-8")
        if source_json.exists():
            payload = json.loads(source_json.read_text(encoding="utf-8"))
            payload["inventory_name"] = after_state["inventory_name"]
            payload["self_healed_from"] = relaxed["inventory_name"]
            payload["self_healed_at"] = utc_now()
            payload["self_heal_reason"] = "empty_selected_relaxed_filters"
            target_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    except Exception:
        pause_inventory(job, reason="self_heal_copy_failed")
        return False
    print(
        f"[INVENTORY SELF-HEAL] {after_state['inventory_name']} | "
        f"fields={len(load_inventory_fields(job))} | source={relaxed['inventory_name']}"
    )
    stamp_inventory_compatibility(job)
    return len(load_inventory_fields(job)) > 0


def hydrate_inventory_from_related(job: dict) -> bool:
    inventory_name = str(job.get("inventory_name") or job.get("name") or Path(str(job.get("template"))).stem)
    category = str(job.get("category") or "").lower()
    related_fields: dict[str, dict] = {}
    related_sources: list[str] = []

    if not INVENTORY_DIR.exists():
        return False

    for inventory_path in sorted(INVENTORY_DIR.glob("*.json")):
        if inventory_path.stem == inventory_name:
            continue
        try:
            payload = json.loads(inventory_path.read_text(encoding="utf-8"))
        except Exception:
            continue
        payload_category = str(payload.get("category") or "").lower()
        stem_related = inventory_path.stem.startswith(f"{inventory_name}_")
        category_related = bool(category and payload_category == category)
        if not stem_related and not category_related:
            continue
        for field in payload.get("fields") or []:
            compatible, _ = field_is_compatible_with_job(field, job)
            if not compatible:
                continue
            field_id = field.get("id")
            if field_id and field_id not in related_fields:
                related_fields[field_id] = field
        related_sources.append(inventory_path.name)

    if not related_fields:
        return False

    output_payload = {
        "inventory_name": inventory_name,
        "template": str(job.get("template") or ""),
        "search_scope": {
            "instrumentType": job.get("instrument_type") or "EQUITY",
            "region": job.get("region") or "USA",
            "delay": job.get("delay") or 1,
            "universe": job.get("universe") or "TOP3000",
        },
        "dataset_id": job.get("dataset_id"),
        "category": job.get("category"),
        "search": job.get("search"),
        "selection_query": job.get("selection_query"),
        "fetch_limit": job.get("inventory_fetch_limit") or job.get("limit"),
        "selection_limit": job.get("selection_limit"),
        "min_selection_score": job.get("min_selection_score"),
        "raw_record_count": len(related_fields),
        "filtered_record_count": len(related_fields),
        "selected_record_count": len(related_fields),
        "compatible_record_count": len(related_fields),
        "compatibility_checked_at": utc_now(),
        "hydrated_from_related_inventories": related_sources,
        "fields": list(related_fields.values()),
    }
    INVENTORY_DIR.mkdir(parents=True, exist_ok=True)
    json_path = inventory_json_for(job)
    txt_path = inventory_file_for(job)
    json_path.write_text(json.dumps(output_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    txt_path.write_text(
        "\n".join(field["id"] for field in output_payload["fields"] if field.get("id")) + "\n",
        encoding="utf-8",
    )
    print(
        f"[INVENTORY HYDRATE] {inventory_name} | fields={len(output_payload['fields'])} | "
        f"sources={len(related_sources)}"
    )
    return True


def should_refresh_inventory(job: dict, min_pool_size: int) -> tuple[bool, dict]:
    paused, pause_row = inventory_is_paused(job)
    if paused:
        inventory_state = load_inventory_state(job)
        inventory_state["paused"] = True
        inventory_state["pause_reason"] = pause_row.get("reason")
        inventory_state["paused_until"] = pause_row.get("paused_until")
        return False, inventory_state

    if not job.get("refresh_inventory", True):
        return False, load_inventory_state(job)

    inventory_state = load_inventory_state(job)
    allow_hydration = not bool(job.get("disable_related_hydration"))
    if not inventory_state["inventory_exists"] and allow_hydration:
        hydrated = hydrate_inventory_from_related(job)
        if hydrated:
            inventory_state = load_inventory_state(job)

    if not inventory_state["inventory_exists"]:
        return True, inventory_state

    if int(inventory_state.get("incompatible_count") or 0) > 0:
        kept_count = sanitize_inventory_to_compatible_fields(job)
        if kept_count >= min_pool_size:
            return False, load_inventory_state(job)
        print(
            f"[INVENTORY REBUILD] {inventory_state['inventory_name']} | "
            f"incompatible_fields={inventory_state.get('incompatible_count')} | "
            f"types={inventory_state.get('field_type_counts')} | "
            f"sample={inventory_state.get('sample_incompatible')}"
        )
        return True, inventory_state

    if bool(job.get("rebuild_if_hydrated")) and inventory_state.get("hydrated_from_related"):
        return True, inventory_state

    requested_min_coverage = job.get("min_coverage")
    stored_min_coverage = inventory_state.get("min_coverage")
    if requested_min_coverage is not None:
        try:
            requested = float(requested_min_coverage)
            stored = float(stored_min_coverage or 0.0)
        except Exception:
            requested = 0.0
            stored = 0.0
        if stored + 1e-9 < requested:
            return True, inventory_state

    min_remaining = int(job.get("inventory_reuse_min_remaining") or max(min_pool_size, 1))
    stale_after_minutes = job.get("inventory_stale_after_minutes")
    if inventory_state["pool_size"] < min_remaining:
        return True, inventory_state
    if stale_after_minutes is not None and inventory_state["age_minutes"] is not None:
        if inventory_state["age_minutes"] >= float(stale_after_minutes):
            return True, inventory_state
    return False, inventory_state


def build_inventory_command(job: dict) -> list[str]:
    template = job.get("template")
    inventory_name = str(job.get("inventory_name") or job.get("name") or Path(str(template)).stem)
    command = [
        sys.executable,
        str(SCRIPT_DIR / "build_template_field_inventory.py"),
        str(template),
        "--name",
        inventory_name,
    ]
    flags = {
        "--instrument-type": job.get("instrument_type"),
        "--region": job.get("region"),
        "--delay": job.get("delay"),
        "--universe": job.get("universe"),
        "--fetch-limit": job.get("inventory_fetch_limit") or job.get("limit"),
        "--dataset-id": job.get("dataset_id"),
        "--category": job.get("category"),
        "--search": job.get("search"),
        "--min-coverage": job.get("min_coverage"),
        "--max-alpha-count": job.get("max_alpha_count"),
        "--max-user-count": job.get("max_user_count"),
        "--field-order": job.get("field_order"),
        "--selection-query": job.get("selection_query"),
        "--selection-limit": job.get("selection_limit"),
        "--min-selection-score": job.get("min_selection_score"),
        "--dataset-categories": job.get("dataset_categories"),
        "--max-datasets": job.get("max_datasets"),
        "--per-dataset-limit": job.get("per_dataset_limit"),
    }
    for flag, value in flags.items():
        if value is not None:
            command.extend([flag, str(value)])
    if job.get("discover_datasets"):
        command.append("--discover-datasets")
    return command


def ensure_inventory(job: dict, min_pool_size: int) -> bool:
    specs = slot_inventory_specs(job)
    if specs:
        ok = True
        for slot, spec in specs.items():
            refresh_inventory, inventory_state = should_refresh_inventory(spec, min_pool_size=min_pool_size)
            print(
                f"[INVENTORY CHECK] {inventory_state['inventory_name']} | slot={slot} | refresh={refresh_inventory} | "
                f"selected={inventory_state['selected_count']} | completed={inventory_state['completed_count']} | "
                f"pool_size={inventory_state['pool_size']} | age_minutes={inventory_state['age_minutes']} | "
                f"paused={bool(inventory_state.get('paused'))}"
            )
            if inventory_state.get("paused"):
                ok = False
                continue
            if not refresh_inventory and inventory_state["selected_count"] >= min_pool_size:
                continue
            ok = ok and build_inventory_with_fallback(spec, inventory_state, min_pool_size=min_pool_size)
        return ok

    fixed_slots = fixed_expression_slots(job)
    if fixed_slots == []:
        return True

    refresh_inventory, inventory_state = should_refresh_inventory(job, min_pool_size=min_pool_size)
    print(
        f"[INVENTORY CHECK] {inventory_state['inventory_name']} | refresh={refresh_inventory} | "
        f"selected={inventory_state['selected_count']} | completed={inventory_state['completed_count']} | "
        f"pool_size={inventory_state['pool_size']} | age_minutes={inventory_state['age_minutes']} | "
        f"paused={bool(inventory_state.get('paused'))}"
    )
    if inventory_state.get("paused"):
        return False
    if not refresh_inventory and inventory_state["selected_count"] >= min_pool_size:
        return True
    return build_inventory_with_fallback(job, inventory_state, min_pool_size=min_pool_size)


def resolve_template(path_text: str) -> Path:
    path = Path(path_text)
    if not path.exists():
        path = ROOT_DIR / path_text
    return path.resolve()


def fixed_expression_slots(job: dict) -> list[str] | None:
    if is_high_grade_repair_job(job):
        template_path = resolve_template(str(job["template"]))
        template = load_template(template_path)
        slots = extract_field_slots(template)
        if not slots:
            return []
        return slots
    if not bool(job.get("fixed_expression_template")):
        return None
    template_path = resolve_template(str(job["template"]))
    template = load_template(template_path)
    return extract_field_slots(template)


@dataclass
class Candidate:
    job_name: str
    supply_mode: str
    mechanism_id: str
    raw_alpha_family: str
    template_path: Path
    fields: dict[str, str]
    config: dict
    fingerprint: str

    @property
    def key(self) -> str:
        slot_key = ",".join(f"{slot}={self.fields[slot]}" for slot in sorted(self.fields))
        return f"{self.job_name}:{self.template_path.name}:{slot_key}"


def build_candidate(job: dict, field_map: dict[str, str]) -> Candidate | None:
    template_path = resolve_template(str(job["template"]))
    template = load_template(template_path)
    validation = validate_template_payload(template_path, template)
    if not validation.valid:
        print(f"TEMPLATE INVALID | {template_path} | {'; '.join(validation.errors)}")
        return None
    config = replace_field_map(template, field_map)
    fingerprint = build_alpha_fingerprint(config)
    return Candidate(
        job_name=str(job.get("name") or template_path.stem),
        supply_mode=str(job.get("supply_mode") or "explore"),
        mechanism_id=str(job.get("mechanism_id") or job.get("research_mechanism_id") or ""),
        raw_alpha_family=str(job.get("raw_alpha_family") or ""),
        template_path=template_path,
        fields=dict(field_map),
        config=config,
        fingerprint=fingerprint,
    )


def slot_fields_for_job(job: dict) -> list[str]:
    slot_specs = slot_inventory_specs(job)
    if slot_specs:
        return sorted(str(slot) for slot in slot_specs.keys())
    template_path = resolve_template(str(job["template"]))
    template = load_template(template_path)
    slots = extract_field_slots(template)
    if (bool(job.get("fixed_expression_template")) or is_high_grade_repair_job(job)) and not slots:
        return []
    return slots or ["FIELD"]


def iter_field_maps(job: dict, max_pairs: int = 600, blocked_fields: set[str] | None = None) -> list[dict[str, str]]:
    blocked_fields = blocked_fields or set()
    slots = slot_fields_for_job(job)
    if not slots:
        return [{}]
    slot_specs = slot_inventory_specs(job)
    if slot_specs:
        slot_fields: dict[str, list[str]] = {}
        for slot in slots:
            fields = [field for field in load_slot_inventory_fields(job, slot) if field not in blocked_fields]
            random.shuffle(fields)
            if not fields:
                return []
            slot_fields[slot] = fields[: min(len(fields), 50)]

        if len(slots) == 1:
            return [{slots[0]: field} for field in slot_fields[slots[0]]]

        combinations: list[dict[str, str]] = []
        seen: set[tuple[str, ...]] = set()
        job_max_pairs = int(job.get("max_pair_field_maps") or max_pairs)
        max_attempts = max(job_max_pairs * 20, 400)
        attempts = 0
        while len(combinations) < job_max_pairs and attempts < max_attempts:
            attempts += 1
            mapping = {slot: random.choice(slot_fields[slot]) for slot in slots}
            values = [mapping[slot] for slot in slots]
            if len(set(values)) != len(values):
                continue
            key = tuple(values)
            if key in seen:
                continue
            seen.add(key)
            combinations.append(mapping)
        return combinations

    fields = [field for field in load_inventory_fields(job) if field not in blocked_fields]
    random.shuffle(fields)
    if not fields:
        return []
    if len(slots) == 1:
        return [{slots[0]: field} for field in fields]

    trimmed = fields[: min(len(fields), 40)]
    combinations: list[dict[str, str]] = []
    seen: set[tuple[str, ...]] = set()
    job_max_pairs = int(job.get("max_pair_field_maps") or max_pairs)
    if len(slots) == 2:
        for left in trimmed:
            for right in trimmed:
                if left == right:
                    continue
                key = (left, right)
                if key in seen:
                    continue
                seen.add(key)
                combinations.append({slots[0]: left, slots[1]: right})
                if len(combinations) >= job_max_pairs:
                    return combinations
        return combinations

    for field in trimmed:
        mapping = {slot: field for slot in slots}
        combinations.append(mapping)
        if len(combinations) >= job_max_pairs:
            break
    return combinations


def active_mechanism_order(jobs: list[dict], miner_cfg: dict) -> list[str]:
    configured = [
        str(item).strip()
        for item in (miner_cfg.get("mechanism_rotation_order") or [])
        if str(item).strip()
    ]
    present = {
        str(job.get("mechanism_id") or job.get("research_mechanism_id") or "").strip()
        for job in jobs
        if str(job.get("mechanism_id") or job.get("research_mechanism_id") or "").strip()
    }
    ordered = [item for item in configured if item in present]
    ordered.extend(sorted(present - set(ordered)))
    return ordered


def next_target_mechanism(jobs: list[dict], state: dict, miner_cfg: dict) -> str:
    if not bool(miner_cfg.get("mechanism_rotation_enabled", True)):
        return ""
    mechanisms = active_mechanism_order(jobs, miner_cfg)
    if not mechanisms:
        return ""
    cursor = int(state.get("mechanism_cursor") or 0) % len(mechanisms)
    state["mechanism_cursor"] = (cursor + 1) % len(mechanisms)
    return mechanisms[cursor]


def job_mechanism(job: dict) -> str:
    return str(job.get("mechanism_id") or job.get("research_mechanism_id") or "").strip()


def is_high_grade_repair_job(job: dict) -> bool:
    return str(job.get("repair_engine") or "") == "high_grade_failed_repair"


def running_repair_count(running: dict) -> int:
    count = 0
    for meta in running.values():
        candidate = meta.get("candidate")
        if candidate is None:
            continue
        if str(candidate.job_name or "").lower().startswith("repair_"):
            count += 1
    return count


def ordered_jobs_for_plan(
    jobs: list[dict],
    desired_mode: str,
    state: dict,
    miner_cfg: dict,
    target_mechanism: str = "",
) -> list[dict]:
    optimizer = ensure_optimizer_state(state, miner_cfg)
    exploration_rate = float(optimizer.get("exploration_rate") or 0.28)
    repair_jobs = [job for job in jobs if is_high_grade_repair_job(job)]
    regular_jobs = [job for job in jobs if not is_high_grade_repair_job(job)]
    mode_matching = [job for job in regular_jobs if str(job.get("supply_mode") or "explore") == desired_mode]
    mode_fallback = [job for job in regular_jobs if job not in mode_matching]
    target_mechanism = str(target_mechanism or "").strip()

    def sort_repair_jobs(rows: list[dict]) -> list[dict]:
        rows = list(rows)
        rows.sort(
            key=lambda job: (
                _safe_float(job.get("supply_priority")),
                -int(job.get("supply_order") or 0),
            ),
            reverse=True,
        )
        return rows

    def sort_jobs(rows: list[dict]) -> list[dict]:
        rows = list(rows)
        rows.sort(key=lambda job: job_sampling_score(job, state, exploration_rate), reverse=True)
        return rows

    if not target_mechanism:
        return sort_repair_jobs(repair_jobs) + sort_jobs(mode_matching) + sort_jobs(mode_fallback)

    primary = [job for job in mode_matching if job_mechanism(job) == target_mechanism]
    secondary = [job for job in mode_fallback if job_mechanism(job) == target_mechanism]
    remaining_matching = [job for job in mode_matching if job_mechanism(job) != target_mechanism]
    remaining_fallback = [job for job in mode_fallback if job_mechanism(job) != target_mechanism]
    return (
        sort_repair_jobs(repair_jobs)
        + sort_jobs(primary)
        + sort_jobs(secondary)
        + sort_jobs(remaining_matching)
        + sort_jobs(remaining_fallback)
    )


def choose_candidate(
    jobs: list[dict],
    desired_mode: str,
    attempted_fingerprints: set[str],
    attempted_keys: set[str],
    known_bad_fingerprints: set[str],
    known_bad_keys: set[str],
    tested_fingerprints: set[str],
    min_pool_size: int,
    allow_inventory_build: bool = True,
    template_error_counts: dict[str, int] | None = None,
    max_template_errors: int = 3,
    state: dict | None = None,
    miner_cfg: dict | None = None,
    scan_stats: dict | None = None,
    target_mechanism: str = "",
) -> Candidate | None:
    template_error_counts = template_error_counts or {}
    state = state or {}
    miner_cfg = miner_cfg or {}
    scan_stats = scan_stats if scan_stats is not None else {}
    scan_stats.setdefault("jobs_considered", 0)
    scan_stats.setdefault("inventory_missing", 0)
    scan_stats.setdefault("inventory_build_failed", 0)
    scan_stats.setdefault("template_error_limit", 0)
    scan_stats.setdefault("candidate_duplicate_key", 0)
    scan_stats.setdefault("candidate_duplicate_fingerprint", 0)
    scan_stats.setdefault("candidate_already_tested", 0)
    scan_stats.setdefault("candidate_known_bad", 0)
    scan_stats.setdefault("template_invalid", 0)
    scan_stats.setdefault("field_maps_scanned", 0)
    scan_stats.setdefault("repair_slot_throttled", 0)
    if target_mechanism:
        scan_stats["target_mechanism"] = target_mechanism
    repair_slot_limit = int(miner_cfg.get("repair_active_slot_limit", 0) or 0)
    current_repair_running = int(state.get("repair_running_count") or 0)
    for job in ordered_jobs_for_plan(jobs, desired_mode, state, miner_cfg, target_mechanism=target_mechanism):
        scan_stats["jobs_considered"] += 1
        if repair_slot_limit > 0 and is_high_grade_repair_job(job) and current_repair_running >= repair_slot_limit:
            scan_stats["repair_slot_throttled"] += 1
            continue
        if allow_inventory_build:
            if not ensure_inventory(job, min_pool_size=min_pool_size):
                scan_stats["inventory_build_failed"] += 1
                continue
        elif fixed_expression_slots(job) == []:
            pass
        elif not load_inventory_fields(job):
            scan_stats["inventory_missing"] += 1
            continue
        for field_map in iter_field_maps(job, blocked_fields=bad_field_set(state)):
            scan_stats["field_maps_scanned"] += 1
            candidate = build_candidate(job, field_map)
            if candidate is None:
                scan_stats["template_invalid"] += 1
                continue
            template_key = str(candidate.template_path.relative_to(ROOT_DIR))
            if int(template_error_counts.get(template_key) or 0) >= max_template_errors:
                scan_stats["template_error_limit"] += 1
                continue
            if candidate.key in known_bad_keys or candidate.fingerprint in known_bad_fingerprints:
                scan_stats["candidate_known_bad"] += 1
                continue
            if candidate.key in attempted_keys:
                scan_stats["candidate_duplicate_key"] += 1
                continue
            if candidate.fingerprint in attempted_fingerprints or candidate.fingerprint in tested_fingerprints:
                if candidate.fingerprint in tested_fingerprints:
                    scan_stats["candidate_already_tested"] += 1
                else:
                    scan_stats["candidate_duplicate_fingerprint"] += 1
                continue
            return candidate
    return None


def structural_error_family_threshold_reached(
    state: dict,
    family: str,
    error_kind: str,
    threshold: int,
) -> bool:
    if threshold <= 0 or not family or not error_kind:
        return False
    recent = list(state.get("history") or [])[-400:]
    # The caller invokes this before appending the current failure to history,
    # so start at one to include the triggering event.
    matched = 1
    for row in reversed(recent):
        if not isinstance(row, dict):
            continue
        if row.get("status") != "error":
            continue
        if str(row.get("raw_alpha_family") or "") != family:
            continue
        if str(row.get("error_kind") or "") != error_kind:
            continue
        matched += 1
        if matched >= threshold:
            return True
    return False


def choose_repair_candidate(
    jobs: list[dict],
    attempted_fingerprints: set[str],
    attempted_keys: set[str],
    known_bad_fingerprints: set[str],
    known_bad_keys: set[str],
    tested_fingerprints: set[str],
    min_pool_size: int,
    allow_inventory_build: bool,
    template_error_counts: dict[str, int] | None,
    max_template_errors: int,
    state: dict,
    miner_cfg: dict,
    scan_stats: dict | None = None,
) -> Candidate | None:
    """Force-fill the protected repair slot when fresh repair work exists."""
    repair_jobs = [job for job in jobs if is_high_grade_repair_job(job)]
    if scan_stats is not None:
        scan_stats["repair_jobs_available"] = len(repair_jobs)
    if not repair_jobs:
        return None
    return choose_candidate(
        jobs=repair_jobs,
        desired_mode="exploit",
        attempted_fingerprints=attempted_fingerprints,
        attempted_keys=attempted_keys,
        known_bad_fingerprints=known_bad_fingerprints,
        known_bad_keys=known_bad_keys,
        tested_fingerprints=tested_fingerprints,
        min_pool_size=min_pool_size,
        allow_inventory_build=allow_inventory_build,
        template_error_counts=template_error_counts,
        max_template_errors=max_template_errors,
        state=state,
        miner_cfg=miner_cfg,
        scan_stats=scan_stats,
        target_mechanism="",
    )


def get_session(force_refresh: bool = False):
    now = time.time()
    created_at = float(getattr(THREAD_LOCAL, "session_created_at", 0.0) or 0.0)
    needs_refresh = force_refresh or not hasattr(THREAD_LOCAL, "session") or (created_at and (now - created_at) >= SESSION_REFRESH_SECONDS)
    if needs_refresh:
        invalidate_session()
        username, password = load_credentials(CREDENTIALS_FILE)
        THREAD_LOCAL.session = login(username, password)
        THREAD_LOCAL.session_created_at = now
    return THREAD_LOCAL.session


def submit_candidate(
    candidate: Candidate,
    sync_platform_color: bool,
    check_retries: int = 0,
    check_retry_delay_seconds: int = 8,
) -> dict:
    field_label = ",".join(candidate.fields[slot] for slot in sorted(candidate.fields))
    config_tags = {str(tag).upper() for tag in (candidate.config.get("tags") or [])}
    sync_family_tags = "1REPAIR" in config_tags or any(tag.startswith("FAM_") for tag in config_tags)
    kwargs = {
        "config": candidate.config,
        "source_label": f"{candidate.template_path.name}:{field_label}",
        "source_file": f"<slot_miner:{candidate.job_name}:{candidate.template_path.name}:{field_label}>",
        "fallback_name": slugify("_".join(candidate.fields[slot] for slot in sorted(candidate.fields))),
        "check_retries": check_retries,
        "check_retry_delay_seconds": check_retry_delay_seconds,
        "sync_platform_properties": sync_family_tags,
        "sync_platform_color": sync_platform_color,
        "batch_name": f"slot_{candidate.job_name}",
        "storage_mode": "light",
    }
    attempts = 2
    for attempt in range(1, attempts + 1):
        session = get_session(force_refresh=(attempt > 1))
        try:
            return submit_alpha_config(session=session, **kwargs)
        except Exception as exc:
            if attempt < attempts and is_auth_error(exc):
                print(f"[AUTH RECOVERY] {candidate.job_name} | refreshing expired session and retrying once.")
                invalidate_session()
                continue
            raise


def main() -> None:
    parser = argparse.ArgumentParser(description="Run slot-level continuous alpha mining.")
    parser.add_argument("config", help="Continuous orchestrator YAML config")
    parser.add_argument("--once", action="store_true", help="Fill slots once, then stop after active tasks finish")
    parser.add_argument("--max-completed", type=int, help="Stop after this many new completed tasks")
    parser.add_argument("--dry-run-candidates", type=int, help="Print this many candidates without submitting")
    args = parser.parse_args()

    config_path = Path(args.config).resolve()
    config = load_config(config_path)
    miner_cfg = config.get("slot_miner") or {}
    miner_name = str(miner_cfg.get("name") or f"{config.get('name') or config_path.stem}_slot_miner")
    state_path = state_path_for(miner_name)
    state = load_state(state_path)

    slot_plan = list(miner_cfg.get("slot_plan") or ["explore", "exploit", "explore", "exploit"])
    max_slots = int(miner_cfg.get("max_slots") or (config.get("supply") or {}).get("active_job_slots", 3))
    refill_sleep_seconds = int(miner_cfg.get("refill_sleep_seconds", 5))
    supply_refresh_seconds = int(miner_cfg.get("supply_refresh_seconds", 600))
    min_pool_size = int(miner_cfg.get("min_pool_size", 1))
    sync_platform_color = bool(miner_cfg.get("sync_platform_color", True))
    check_retries = int(miner_cfg.get("check_retries", 6))
    check_retry_delay_seconds = int(miner_cfg.get("check_retry_delay_seconds", 20))
    max_template_errors = int(miner_cfg.get("max_template_errors", 3))
    structural_family_error_pause_threshold = int(miner_cfg.get("structural_family_error_pause_threshold", 18))
    stale_submit_recovery_minutes = int(miner_cfg.get("stale_submit_recovery_minutes", 30))
    optimizer = ensure_optimizer_state(state, miner_cfg)
    plan_index = int(state.get("plan_index") or 0)
    last_supply_refresh = 0.0
    attempt_fingerprint_limit = int(miner_cfg.get("attempted_fingerprint_limit", 1200))
    attempt_key_limit = int(miner_cfg.get("attempted_key_limit", 2400))
    known_bad_fingerprint_limit = int(miner_cfg.get("known_bad_fingerprint_limit", 5000))
    known_bad_key_limit = int(miner_cfg.get("known_bad_key_limit", 8000))

    print(f"Continuous slot miner: {miner_name}")
    print(f"Config: {config_path}")
    print(f"State: {state_path}")
    print(f"Slot plan: {slot_plan}")

    if args.dry_run_candidates:
        build_supply(config_path)
        jobs = load_supply_jobs()
        attempted_fingerprints = set(state.get("attempted_fingerprints") or [])
        attempted_keys = set(state.get("attempted_keys") or [])
        known_bad_fingerprints = set(state.get("known_bad_fingerprints") or [])
        known_bad_keys = set(state.get("known_bad_keys") or [])
        tested_fingerprints = load_tested_fingerprints()
        print("=" * 80)
        print("DRY RUN CANDIDATES")
        for index in range(args.dry_run_candidates):
            desired_mode = choose_desired_mode(slot_plan[index % len(slot_plan)], {}, state, miner_cfg)
            target_mechanism = next_target_mechanism(jobs, state, miner_cfg)
            candidate = choose_candidate(
                jobs=jobs,
                desired_mode=desired_mode,
                attempted_fingerprints=attempted_fingerprints,
                attempted_keys=attempted_keys,
                known_bad_fingerprints=known_bad_fingerprints,
                known_bad_keys=known_bad_keys,
                tested_fingerprints=tested_fingerprints,
                min_pool_size=min_pool_size,
                allow_inventory_build=False,
                template_error_counts=state.get("template_error_counts") or {},
                max_template_errors=max_template_errors,
                state=state,
                miner_cfg=miner_cfg,
                target_mechanism=target_mechanism,
            )
            if candidate is None:
                print(f"{index + 1}. no candidate for plan={desired_mode}")
                break
            attempted_fingerprints.add(candidate.fingerprint)
            attempted_keys.add(candidate.key)
            print(
                f"{index + 1}. plan={desired_mode} mode={candidate.supply_mode} "
                f"target_mechanism={target_mechanism or '-'} mechanism={candidate.mechanism_id or '-'} "
                f"job={candidate.job_name} fields={candidate.fields} "
                f"template={candidate.template_path.name} fingerprint={candidate.fingerprint[:80]}"
            )
        print("=" * 80)
        return

    running: dict = {}
    executor = ThreadPoolExecutor(max_workers=max(1, max_slots))
    try:
        while True:
            if not SUPPLY_JOBS_FILE.exists() or (datetime.now(timezone.utc).timestamp() - last_supply_refresh) >= supply_refresh_seconds:
                build_supply(config_path)
                last_supply_refresh = datetime.now(timezone.utc).timestamp()

            jobs = load_supply_jobs()
            supply_summary = load_supply_summary()
            if not jobs:
                print("No supply jobs available. Sleeping before retry...")
                sleep(max(refill_sleep_seconds, 10))
                continue
            supply_generation = int(supply_summary.get("generation_id") or 0)
            if reset_attempt_tracking_for_generation(
                state,
                generation_id=supply_generation,
                fingerprint_limit=attempt_fingerprint_limit,
                key_limit=attempt_key_limit,
            ):
                print(
                    "Attempt tracking reset:",
                    f"generation={supply_generation}",
                )
                save_state(state_path, state)

            adaptive = choose_adaptive_limits(config, max_slots)
            active_slots = max(1, int(adaptive["active_job_slots"]))
            configured_repair_slot_limit = int(miner_cfg.get("repair_active_slot_limit", 0) or 0)
            if configured_repair_slot_limit <= 0:
                repair_slot_limit = max(1, int(math.ceil(active_slots * 0.3)))
            else:
                repair_slot_limit = max(1, min(configured_repair_slot_limit, active_slots))
            tested_fingerprints = load_tested_fingerprints()
            attempted_fingerprints = set(state.get("attempted_fingerprints") or [])
            attempted_keys = set(state.get("attempted_keys") or [])
            known_bad_fingerprints = set(state.get("known_bad_fingerprints") or [])
            known_bad_keys = set(state.get("known_bad_keys") or [])
            if recover_stale_submission_flow(
                state=state,
                supply_summary=supply_summary,
                stale_minutes=stale_submit_recovery_minutes,
                active_running=len(running),
            ):
                attempted_fingerprints = set()
                attempted_keys = set()
                print(
                    "Stale submit recovery:",
                    f"generation={int(supply_summary.get('generation_id') or 0)}",
                    f"stale_submit_recovery_minutes={stale_submit_recovery_minutes}",
                )
                save_state(state_path, state)
            print(
                "Slot miner status:",
                f"adaptive={adaptive['mode']}",
                f"recent_429={adaptive['event_count']}",
                f"running={len(running)}",
                f"target_active={active_slots}",
                f"repair_running={running_repair_count(running)}/{repair_slot_limit}",
                f"supply_jobs={int(supply_summary.get('job_count') or len(jobs))}",
                f"generation={int(supply_summary.get('generation_id') or 0)}",
                f"explore_jobs={int(supply_summary.get('explore_job_count') or 0)}",
                f"exploit_jobs={int(supply_summary.get('exploit_job_count') or 0)}",
                f"supply_templates={int(supply_summary.get('template_count') or 0)}",
                f"bandit_categories={len(((supply_summary.get('hierarchical_bandit') or {}).get('category_bandit')) or {})}",
                f"bandit_strategies={len(((supply_summary.get('hierarchical_bandit') or {}).get('strategy_bandit')) or {})}",
                f"bandit_operators={len(((supply_summary.get('hierarchical_bandit') or {}).get('operator_bandit')) or {})}",
                f"population_families={int(((supply_summary.get('population_summary') or {}).get('family_count')) or 0)}",
                f"degrading_families={int(((supply_summary.get('population_summary') or {}).get('degrading_family_count')) or 0)}",
                f"retired_families={int(((supply_summary.get('population_summary') or {}).get('retired_family_count')) or 0)}",
                f"active_lineages={int(((supply_summary.get('lineage_summary') or {}).get('family_job_count')) or 0)}",
                f"warehouse_lineages={int(((supply_summary.get('lineage_warehouse_summary') or {}).get('lineage_count')) or 0)}",
                f"warehouse_offspring={int(((supply_summary.get('lineage_warehouse_summary') or {}).get('offspring_count')) or 0)}",
                f"pair_jobs={int(((supply_summary.get('generation_summary') or {}).get('pair_jobs')) or 0)}",
                f"lateral_jobs={int(((supply_summary.get('generation_summary') or {}).get('lateral_jobs')) or 0)}",
                f"mutation_jobs={int(((supply_summary.get('generation_summary') or {}).get('mutation_jobs')) or 0)}",
                f"crossover_jobs={int(((supply_summary.get('generation_summary') or {}).get('crossover_jobs')) or 0)}",
                f"exploration_rate={optimizer.get('exploration_rate')}",
                f"attempted={len(attempted_fingerprints)}",
                f"known_bad={len(known_bad_fingerprints)}",
                f"tested={len(tested_fingerprints)}",
            )

            while len(running) < active_slots:
                scan_stats = {}
                desired_mode = choose_desired_mode(
                    slot_plan[plan_index % len(slot_plan)],
                    supply_summary,
                    state,
                    miner_cfg,
                )
                target_mechanism = next_target_mechanism(jobs, state, miner_cfg)
                plan_index += 1
                state["repair_running_count"] = running_repair_count(running)
                force_repair_slot = state["repair_running_count"] < repair_slot_limit
                candidate = None
                if force_repair_slot:
                    candidate = choose_repair_candidate(
                        jobs=jobs,
                        attempted_fingerprints=attempted_fingerprints,
                        attempted_keys=attempted_keys,
                        known_bad_fingerprints=known_bad_fingerprints,
                        known_bad_keys=known_bad_keys,
                        tested_fingerprints=tested_fingerprints,
                        min_pool_size=min_pool_size,
                        allow_inventory_build=True,
                        template_error_counts=state.get("template_error_counts") or {},
                        max_template_errors=max_template_errors,
                        state=state,
                        miner_cfg={**miner_cfg, "repair_active_slot_limit": repair_slot_limit},
                        scan_stats=scan_stats,
                    )
                    if candidate is None:
                        scan_stats["repair_force_slot_miss"] = 1
                if candidate is None:
                    candidate = choose_candidate(
                        jobs=jobs,
                        desired_mode=desired_mode,
                        attempted_fingerprints=attempted_fingerprints,
                        attempted_keys=attempted_keys,
                        known_bad_fingerprints=known_bad_fingerprints,
                        known_bad_keys=known_bad_keys,
                        tested_fingerprints=tested_fingerprints,
                        min_pool_size=min_pool_size,
                        allow_inventory_build=True,
                        template_error_counts=state.get("template_error_counts") or {},
                        max_template_errors=max_template_errors,
                        state=state,
                        miner_cfg={**miner_cfg, "repair_active_slot_limit": repair_slot_limit},
                        scan_stats=scan_stats,
                        target_mechanism=target_mechanism,
                    )
                if candidate is None:
                    state["candidate_scan_stats"] = {
                        **scan_stats,
                        "desired_mode": desired_mode,
                        "target_mechanism": target_mechanism,
                        "force_repair_slot": force_repair_slot,
                        "ts": utc_now(),
                    }
                    raw_rotation = supply_summary.get("raw_alpha_rotation") or {}
                    selected_raw_families = [
                        str(item)
                        for item in (raw_rotation.get("selected_families") or [])
                        if str(item)
                    ]
                    no_candidate_state = state.setdefault("no_candidate_fuse", {})
                    family_key = ",".join(selected_raw_families) or "unknown"
                    if no_candidate_state.get("family_key") != family_key:
                        no_candidate_state = {"family_key": family_key, "count": 0, "first_seen_at": utc_now()}
                    no_candidate_state["count"] = int(no_candidate_state.get("count") or 0) + 1
                    no_candidate_state["last_seen_at"] = utc_now()
                    no_candidate_state["last_scan_stats"] = state["candidate_scan_stats"]
                    state["no_candidate_fuse"] = no_candidate_state
                    no_candidate_threshold = max(3, int(miner_cfg.get("raw_family_no_candidate_pause_threshold", 8)))
                    empty_inventory_failures = int(scan_stats.get("inventory_build_failed") or 0)
                    jobs_considered_for_scan = int(scan_stats.get("jobs_considered") or 0)
                    should_pause_raw_family = (
                        selected_raw_families
                        and no_candidate_state["count"] >= no_candidate_threshold
                        and jobs_considered_for_scan > 0
                        and empty_inventory_failures >= jobs_considered_for_scan
                    )
                    if should_pause_raw_family:
                        evidence = {
                            "no_candidate_count": no_candidate_state["count"],
                            "scan_stats": state["candidate_scan_stats"],
                            "supply_generation": int(supply_summary.get("generation_id") or 0),
                        }
                        for raw_family in selected_raw_families:
                            pause_raw_family_by_name(
                                raw_family,
                                "no_candidate_empty_or_paused_inventory",
                                evidence=evidence,
                            )
                        state["attempted_fingerprints"] = []
                        state["attempted_keys"] = []
                        attempted_fingerprints.clear()
                        attempted_keys.clear()
                        last_supply_refresh = 0.0
                    append_history(
                        state,
                        {
                            "ts": utc_now(),
                            "event": "no_candidate_found",
                            **state["candidate_scan_stats"],
                        },
                    )
                    save_state(state_path, state)
                    print(f"No candidate found for plan={desired_mode}.")
                    print(f"Candidate scan stats: {state['candidate_scan_stats']}")
                    break
                attempted_fingerprints.add(candidate.fingerprint)
                attempted_keys.add(candidate.key)
                state["attempted_fingerprints"] = append_recent_unique(
                    list(state.get("attempted_fingerprints") or []),
                    candidate.fingerprint,
                    attempt_fingerprint_limit,
                )
                state["attempted_keys"] = append_recent_unique(
                    list(state.get("attempted_keys") or []),
                    candidate.key,
                    attempt_key_limit,
                )
                if candidate.mechanism_id:
                    mechanism_counts = state.setdefault("mechanism_attempt_counts", {})
                    mechanism_counts[candidate.mechanism_id] = int(mechanism_counts.get(candidate.mechanism_id) or 0) + 1
                state["candidate_scan_stats"] = {
                    **scan_stats,
                    "desired_mode": desired_mode,
                    "target_mechanism": target_mechanism,
                    "force_repair_slot": force_repair_slot,
                    "ts": utc_now(),
                }
                state["plan_index"] = plan_index
                save_state(state_path, state)

                future = executor.submit(
                    submit_candidate,
                    candidate,
                    sync_platform_color,
                    check_retries,
                    check_retry_delay_seconds,
                )
                running[future] = {
                    "candidate": candidate,
                    "started_at": utc_now(),
                    "desired_mode": desired_mode,
                    "target_mechanism": target_mechanism,
                }
                print(
                    f"[SLOT START] {candidate.job_name} | mode={candidate.supply_mode} | "
                    f"mechanism={candidate.mechanism_id or '-'} | target_mechanism={target_mechanism or '-'} | "
                    f"plan={desired_mode} | fields={candidate.fields} | active={len(running)}/{active_slots}"
                )

            if not running:
                sleep(refill_sleep_seconds)
                if args.once:
                    break
                continue

            done, _ = wait(list(running.keys()), timeout=refill_sleep_seconds, return_when=FIRST_COMPLETED)
            for future in done:
                meta = running.pop(future)
                candidate: Candidate = meta["candidate"]
                event = {
                    "finished_at": utc_now(),
                    "started_at": meta["started_at"],
                    "job_name": candidate.job_name,
                    "supply_mode": candidate.supply_mode,
                    "mechanism_id": candidate.mechanism_id,
                    "raw_alpha_family": candidate.raw_alpha_family,
                    "target_mechanism": meta.get("target_mechanism"),
                    "fields": candidate.fields,
                    "template": str(candidate.template_path.relative_to(ROOT_DIR)),
                    "fingerprint": candidate.fingerprint,
                }
                try:
                    result = future.result()
                    state["completed"] = int(state.get("completed") or 0) + 1
                    event["status"] = "completed"
                    event["alpha_id"] = result.get("alpha_id")
                    state["last_submit_at"] = utc_now()
                    state["last_submit_alpha_id"] = result.get("alpha_id")
                    reward = reward_from_result(result)
                    event["reward"] = reward
                    update_job_bandit(state, candidate.job_name, reward, success=True)
                    update_optimizer_from_reward(state, reward, success=True, miner_cfg=miner_cfg)
                    print(
                        f"[SLOT DONE] {candidate.job_name} | mechanism={candidate.mechanism_id or '-'} | fields={candidate.fields} | "
                        f"alpha={result.get('alpha_id')} | completed={state['completed']}"
                    )
                except Exception as exc:
                    state["errors"] = int(state.get("errors") or 0) + 1
                    event["status"] = "error"
                    event["error"] = str(exc)
                    error_kind = classify_error_kind(str(exc))
                    event["error_kind"] = error_kind
                    reward = -0.35
                    event["reward"] = reward
                    update_job_bandit(state, candidate.job_name, reward, success=False)
                    update_optimizer_from_reward(state, reward, success=False, miner_cfg=miner_cfg)
                    template_key = str(candidate.template_path.relative_to(ROOT_DIR))
                    error_counts = state.setdefault("template_error_counts", {})
                    error_counts[template_key] = int(error_counts.get(template_key) or 0) + 1
                    kind_counts = state.setdefault("error_kind_counts", {})
                    kind_counts[error_kind] = int(kind_counts.get(error_kind) or 0) + 1
                    if error_kind == "unknown_variable":
                        bad_field = extract_unknown_variable(str(exc))
                        remember_bad_field(state, bad_field)
                    if error_kind_is_structural(error_kind):
                        known_bad_fingerprints.add(candidate.fingerprint)
                        known_bad_keys.add(candidate.key)
                        state["known_bad_fingerprints"] = append_recent_unique(
                            list(state.get("known_bad_fingerprints") or []),
                            candidate.fingerprint,
                            known_bad_fingerprint_limit,
                        )
                        state["known_bad_keys"] = append_recent_unique(
                            list(state.get("known_bad_keys") or []),
                            candidate.key,
                            known_bad_key_limit,
                        )
                        if structural_error_family_threshold_reached(
                            state=state,
                            family=candidate.raw_alpha_family,
                            error_kind=error_kind,
                            threshold=structural_family_error_pause_threshold,
                        ):
                            pause_raw_family_rotation(
                                candidate.raw_alpha_family,
                                reason="repeated_structural_errors_in_slot_miner",
                                error_kind=error_kind,
                                candidate=candidate,
                            )
                            last_supply_refresh = 0.0
                    disable_operator_from_error(str(exc), source=candidate.job_name)
                    print(
                        f"[SLOT ERROR] {candidate.job_name} | fields={candidate.fields} | "
                        f"kind={error_kind} | {exc}"
                    )
                append_history(state, event)
                save_state(state_path, state)

            if args.max_completed is not None and int(state.get("completed") or 0) >= args.max_completed:
                print("Reached max completed, stopping.")
                break
            if args.once and not running:
                print("Single fill requested and all slots completed, stopping.")
                break
    finally:
        executor.shutdown(wait=True, cancel_futures=False)


if __name__ == "__main__":
    main()
